### ISSUE TITLE
What about my Kirby 3 branch?

### ISSUE THREAD

**Issue by jbeyerstedt** [julien-gargot/kirby-plugin-kirbytextraw#3]
I already adapted this plugin to Kirby 3 about six months ago, but that version lived in it's own branch, because Kirby 2 and Kirby 3 plugins are quite different. (See https://github.com/jbeyerstedt/kirby-plugin-kirbytextRaw/tree/kirby3.)
I'm not mad or anything, but a bit curious, why you opened another repository. Because there were already pull-requests for the kirby3 branch and it seemed to work just fine for Kirby 3 (I don't use Kirby 3 currently, because I don't have the time now to convert my site.)

But as I just added to my Readme, since Kirby 3.1.0 all of the functionality of the plugin has been added to the standard Kirby field methods.
So there is no need for this any more in Kirby 3.

From the Readme: 
Take a look at:
- [$field->kirbytags()](https://getkirby.com/docs/reference/templates/field-methods/kirbytags) to parse KirbyTags, but no Markdown
- (since 3.1.0) [$field->kirbytextinline()](https://getkirby.com/docs/reference/templates/field-methods/kirbytextinline) to parse KirbyTags and Markdown, but in an inline friendly way. This is the functionality, I wanted to achieve, when I created this plugin for Kirby 2.

It's fine, if you want to continue this repository. But I think, that it will be confusing to see different versions of the same plugin.
But then, you must license your fork as GNU GPL v3.0, because I released my code under this license.

**Comment by julien-gargot** [comment]
Hi :)
Yes I remember that you start to port your plugin to v3 because in the beginning you also accepted a pull request from because it wasn’t working due to frequent update in K3 pre versions. It used to work a moment then no more. I had to rewrite everything to make it correctly in K3 latest betas. For convenient reasons I used the same methods name to not had to update my code. I needed an updated repo quickly so I put the code to mine instead of a pull request. Sorry if offended you. I did not try to take credit for it. Your name is all over readme and code since the beginning. I have nothing again the licence too.

But as you noticed, functionality is in kirby’s core now. So this repo will disappear anyway.

**Comment by jbeyerstedt** [comment]
Sorry, that there were still bugs in "my" version. And no, you haven't offended me. The notice in the readme about the "original" version is just fine.
The notice about the license was just a reminder. But this discussion is obsolete by now, because of the changes in Kirby 3.1.0. So just keep it as it is.
